//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamSeasonEnders.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.PlayoffResults = new HashSet<PlayoffResult>();
            this.PlayoffResults1 = new HashSet<PlayoffResult>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Division { get; set; }
        public string Conference { get; set; }
    
        public virtual ICollection<PlayoffResult> PlayoffResults { get; set; }
        public virtual ICollection<PlayoffResult> PlayoffResults1 { get; set; }
    }
}
